=== Omega1001/Bildverwaltung/Bildverwaltung/bildverwaltung.db-data/src/main/resources/bildverwaltung/dbdata/testdata/testData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/testData"
	xmlns:tns="http://www.example.org/testData"
	elementFormDefault="qualified">

    <complexType name="picture">
    	<sequence>
    		<element name="name" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="uri" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="extension" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="height" type="int" minOccurs="1" maxOccurs="1"></element>
    		<element name="width" type="int" minOccurs="1" maxOccurs="1"></element>
    		<element name="comment" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <complexType name="album">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="comment" type="string"></element>
    		<element name="pictures" type="tns:pictureIds" minOccurs="1" maxOccurs="1"/>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>
    <complexType name="testdata">
    	<sequence>
    		<element name="pictures" type="tns:pictures" minOccurs="0" maxOccurs="1"></element>
    		<element name="albums" type="tns:albums" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="TestData" type="tns:testdata"/>	

    <complexType name="pictureIds">
    	<sequence>
    		<element name="id" type="string" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="pictures">
    	<sequence>
    		<element name="picture" type="tns:picture" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="albums">
    	<sequence>
    		<element name="album" type="tns:album" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
</schema>

=== Omega1001/Bildverwaltung/Bildverwaltung/bildverwaltung.db-data/src/main/resources/bildverwaltung/dbdata/testdata/testdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<TestData xmlns="http://www.example.org/testData"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/testData testData.xsd ">
	<pictures>
		<picture id="00000000-0000-0000-0000-000000000000">
			<name>Bearbeiten</name>
			<uri>file:/${fxprojectLocale}/src/main/resources/Bearbeiten.png</uri>
			<extension>png</extension>
			<height>588</height>
			<width>1287</width>
			<comment>This is a comment</comment>
		</picture>
		<picture id="00000000-0000-0000-0000-000000000001">
			<name>Bearbeiten</name>
			<uri>file:/${fxprojectLocale}/src/main/resources/Datei.png</uri>
			<extension>png</extension>
			<height>588</height>
			<width>1287</width>
			<comment>This is a comment</comment>
		</picture>
		<picture id="00000000-0000-0000-0000-000000000002">
			<name>Bearbeiten</name>
			<uri>file:/${fxprojectLocale}/src/main/resources/Diashow.png</uri>
			<extension>png</extension>
			<height>588</height>
			<width>1287</width>
			<comment>This is a comment</comment>
		</picture>
		<picture id="00000000-0000-0000-0000-000000000003">
			<name>Bearbeiten</name>
			<uri>file:/${fxprojectLocale}/src/main/resources/Gro√üansicht.png</uri>
			<extension>png</extension>
			<height>588</height>
			<width>1287</width>
			<comment>This is a comment</comment>
		</picture>
		<picture id="00000000-0000-0000-0000-000000000004">
			<name>Bearbeiten</name>
			<uri>file:/${fxprojectLocale}/src/main/resources/Import.png</uri>
			<extension>png</extension>
			<height>588</height>
			<width>1287</width>
			<comment>This is a comment</comment>
		</picture>
	</pictures>
	<albums>
		<album id="10000000-0000-0000-0000-000000000000">
			<name>name</name>
			<comment>comment</comment>
			<pictures>
				<id>00000000-0000-0000-0000-000000000000</id>
				<id>00000000-0000-0000-0000-000000000001</id>
			</pictures>
		</album>
		<album id="10000000-0000-0000-0000-000000000001">
			<name>name</name>
			<comment>comment</comment>
			<pictures>
				<id>00000000-0000-0000-0000-000000000002</id>
				<id>00000000-0000-0000-0000-000000000003</id>
			</pictures>
		</album>
		<album id="10000000-0000-0000-0000-000000000002">
			<name>name</name>
			<comment>comment</comment>
			<pictures>
				<id>00000000-0000-0000-0000-000000000001/id>
				<id>00000000-0000-0000-0000-000000000002</id>
			</pictures>
		</album>
	</albums>
</TestData>
